# Generated by Django 2.1.3 on 2018-11-25 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtCover', models.URLField()),
                ('ExternalLink', models.URLField()),
                ('ArtTitle', models.CharField(max_length=170, verbose_name='Title')),
                ('ArtSubTitle', models.TextField(blank=True, verbose_name='Subheading')),
                ('UserComment', models.TextField(blank=True, verbose_name='Your comment')),
                ('ArtBlocks', models.IntegerField(default=1, verbose_name='Parts')),
                ('ArtParts', models.IntegerField(default=1, verbose_name='Episodes')),
                ('SolidArt', models.BooleanField(default=False, verbose_name='One Part?')),
                ('UserRating', models.IntegerField(choices=[(0, 'Planned'), (1, 'Amazing'), (2, 'Good'), (3, 'Acceptable'), (4, 'Bad'), (5, 'Horrible')], default=0, verbose_name='Your rating')),
                ('ArtModified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified')),
            ],
            options={
                'ordering': ['-ArtModified'],
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('BlockLabel', models.CharField(default='', max_length=30)),
                ('PartLabel', models.CharField(default='', max_length=30)),
                ('SingleLabel', models.CharField(default='', max_length=100)),
                ('AgoLabel', models.CharField(default='', max_length=70)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artobject',
            name='ArtGeners',
            field=models.ManyToManyField(blank=True, to='ymdb.GenerTag', verbose_name='Geners'),
        ),
        migrations.AddField(
            model_name='artobject',
            name='InCollection',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ymdb.Collections'),
        ),
    ]
