# Generated by Django 2.1.3 on 2018-11-26 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='ArtBlocks',
            field=models.IntegerField(default=1, verbose_name='Томов / Сезонов (и т.п)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtCover',
            field=models.URLField(verbose_name='Обложка (ссылка на изображние)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtGeners',
            field=models.ManyToManyField(blank=True, to='ymdb.GenerTag', verbose_name='Жанры (Тэги) [Сtrl - несколько]'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtModified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtParts',
            field=models.IntegerField(default=1, verbose_name='Эпиозодов / Глав (и т.п)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtSubTitle',
            field=models.TextField(blank=True, max_length=200, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtTitle',
            field=models.CharField(max_length=170, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ExternalLink',
            field=models.URLField(verbose_name='Внешнее описание (ссылка)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='InCollection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ymdb.Collections', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='SolidArt',
            field=models.BooleanField(default=False, verbose_name='Самостоятельное произвдение?'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='UserComment',
            field=models.TextField(blank=True, verbose_name='Ваш комментарий'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='UserRating',
            field=models.IntegerField(choices=[(0, 'Буду смотреть'), (1, 'Отлично'), (2, 'Хорошо'), (3, 'Приемлемо'), (4, 'Плохо'), (5, 'Ужасно')], default=0, verbose_name='Ваша оценка'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='AgoLabel',
            field=models.CharField(default='', max_length=70, verbose_name='Подпись для Даты'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='BlockLabel',
            field=models.CharField(default='', max_length=30, verbose_name='Подпись для Частей'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='PartLabel',
            field=models.CharField(default='', max_length=30, verbose_name='Подпись для Элементов'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='SingleLabel',
            field=models.CharField(default='', max_length=100, verbose_name='Подпись для Самосточтельного произведения'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genertag',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название'),
        ),
    ]
