# Generated by Django 2.1.3 on 2018-11-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0002_auto_20181126_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='ArtParts',
            field=models.IntegerField(default=1, verbose_name='Эпизодов / Глав (и т.п)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='SolidArt',
            field=models.BooleanField(default=False, verbose_name='Самостоятельное произведение?'),
        ),
    ]
