# Generated by Django 2.1.3 on 2018-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0004_auto_20181127_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='UserRating',
            field=models.IntegerField(choices=[(0, 'Буду смотреть'), (5, 'Отлично'), (4, 'Хорошо'), (3, 'Приемлемо'), (2, 'Плохо'), (1, 'Ужасно')], default=0, verbose_name='Ваша оценка'),
        ),
    ]
