# Generated by Django 2.1.3 on 2018-11-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0005_auto_20181127_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='InCollection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ymdb.Collections', verbose_name='Коллекция'),
        ),
    ]
