# Generated by Django 2.1.3 on 2018-11-30 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ymdb', '0006_auto_20181130_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='sysSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageStep', models.IntegerField(default=12, verbose_name='Отбражать по Х карт на странице:')),
                ('theUser', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtBlocks',
            field=models.IntegerField(blank=True, default=1, verbose_name='Томов'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtParts',
            field=models.IntegerField(blank=True, default=1, verbose_name='Эпизодов'),
        ),
    ]
