# Generated by Django 2.1.3 on 2018-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0007_auto_20181201_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='syssettings',
            name='navTheme',
            field=models.CharField(choices=[('navbar-dark bg-dark', 'Тёмная'), ('navbar-light bg-light', 'Светлая'), ('navbar-light bg-primary', 'Серая'), ('navbar-light bg-success', 'Зеленая'), ('navbar-light bg-warning', 'Желатая'), ('navbar-light bg-danger', 'Красная')], default=('navbar-dark bg-dark', 'Тёмная'), max_length=200, verbose_name='Тема тулбара'),
        ),
        migrations.AlterField(
            model_name='syssettings',
            name='pageStep',
            field=models.IntegerField(default=0, verbose_name='Отбражать по Х карт на странице:'),
        ),
    ]
