# Generated by Django 2.1.3 on 2018-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0008_auto_20181201_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='artobject',
            name='ArtCoverCahed',
            field=models.ImageField(default='no_cover.png', upload_to='uploads/covers/', verbose_name='Обложка (*.PNG, *.JPEG)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtGeners',
            field=models.ManyToManyField(blank=True, to='ymdb.GenerTag', verbose_name='Жанры (Тэги)<br><span class="text-muted small">[Сtrl - несколько]</span>'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='SingleLabel',
            field=models.CharField(default='', max_length=100, verbose_name='Подпись для Самостоятельного произведения'),
        ),
        migrations.AlterField(
            model_name='syssettings',
            name='navTheme',
            field=models.CharField(choices=[('navbar-dark bg-dark', 'Тёмная'), ('navbar-light bg-light', 'Светлая'), ('navbar-light alert-secondary border-bottom border-secondary', 'Серая'), ('navbar-light alert-primary border-bottom border-primary', 'Голубая'), ('navbar-light alert-success border-bottom border-success', 'Зеленая'), ('navbar-light alert-warning border-bottom border-warning', 'Желатая'), ('navbar-light alert-danger border-bottom border-danger', 'Красная')], default=('navbar-dark bg-dark', 'Тёмная'), max_length=200, verbose_name='Тема тулбара'),
        ),
    ]
