# Generated by Django 2.1.4 on 2019-04-25 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ymdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0009_auto_20181202_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='guestTestimonilas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsName', models.TextField(blank=True, max_length=100, verbose_name='')),
                ('tsText', models.TextField(blank=True, verbose_name='')),
                ('tsDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isAdmin', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtCover',
            field=models.URLField(blank=True, verbose_name='Обложка (ссылка на изображние)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ArtCoverCahed',
            field=models.ImageField(blank=True, default='', upload_to=ymdb.models.update_filename, verbose_name='Обложка (*.PNG, *.JPEG)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='ExternalLink',
            field=models.URLField(default='https://www.imdb.com/', verbose_name='Внешнее описание (ссылка)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='UserRating',
            field=models.IntegerField(choices=[(-1, '- Скрыть оценку -'), (0, 'Буду смотреть'), (5, 'Отлично'), (4, 'Хорошо'), (3, 'Приемлемо'), (2, 'Плохо'), (1, 'Ужасно')], default=0, verbose_name='Ваша оценка'),
        ),
        migrations.AlterField(
            model_name='syssettings',
            name='pageStep',
            field=models.IntegerField(default=0, verbose_name='Отбражать по Х карт:'),
        ),
        migrations.AddField(
            model_name='guesttestimonilas',
            name='ArtBind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymdb.ArtObject'),
        ),
    ]
