# Generated by Django 2.1.4 on 2019-04-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0010_auto_20190425_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='ExternalLink',
            field=models.URLField(blank=True, default='', verbose_name='Внешняя ссылка (описание или загрузка)'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='UserRating',
            field=models.IntegerField(choices=[(-1, 'Без оценки'), (0, 'Буду смотреть'), (5, 'Отлично'), (4, 'Хорошо'), (3, 'Приемлемо'), (2, 'Плохо'), (1, 'Ужасно')], default=0, verbose_name='Ваша оценка'),
        ),
    ]
